### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by SJGoodson** [githubschool/open-enrollment-classes-introduction-to-github#11483] opened 2017-11-07 17:30 UTC
It says:
1. Open your Pull Request to be merged.

With no other instructions on how to do this.
Trying to make me fail will not keep me here.
Why would you do this? Do you see that if 
one is asking for this tutorial it's because we
do not understand HOW to do this stuff.

Please, please, please, go out to the street 
in front of your office. Grab the first bus driver
you see into your office and pay them to go 
through your tutorial. Do not cheat by saying
anything—no coaching them. See each place
where she says,  "hum, I wonder what that 
means", or "where is that". From this exercise
you will actually see HOW PEOPLE REALLY
interact with your product.

Then Please fix it.

**Comment by hectorsector** [comment] 2017-11-09 01:34
@SJGoodson thanks for the feedback. This is an open source project. We welcome contributions via the [training-kit repository](https://github.com/github/training-kit). 

Since I've responded, I'm marking this issue a duplicate of #11485 so we can keep it all in one place.

**Closed by hectorsector** 2017-11-09 01:34 UTC
Labels: Help Wanted
