### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by SJGoodson** [githubschool/open-enrollment-classes-introduction-to-github#11481] opened 2017-11-07 17:09 UTC
The Jargon that this site uses is really cool an all (if I were 'like 12').
But, is there a dictionary of these terms? 

Me thinking:
A "Branch"? So we will be using a Tree metaphor? Root, branches, leaves, bark, rings, green, brown, etc. etc. etc. Ok, let's go!

A "Pool/Pull request"? It took a bit to release that the video guy was saying "Pull" and not "Pool" (so that should say to you that the term is not a good one!!).  But hold it, "Pull" on the "Branch"? What does that mean? Are we climbing the tree now? Doing Pull ups? Have I climbed up this tree and started pulling something (AHHH!!!)? What am I Pulling and from what perspective? 

You are making me this this application is designed only for the "cool kids". 

Where's the dictionary?
: (

**Comment by SJGoodson** [comment] 2017-11-07 17:10
There it is again, "Repo"!!! What part of the Tree is Repo?????????
This is word-salad. Why? Coolness?

**Comment by hectorsector** [comment] 2017-11-09 01:34
This is a duplicate of #11485. Closing this issue out so we can keep the conversation all in one place.

**Closed by hectorsector** 2017-11-09 01:34 UTC
Labels: Help Wanted
