### ISSUE TITLE
"Issue, we don't need no stinking Issues!"

### ISSUE THREAD

**Issue by SJGoodson** [githubschool/open-enrollment-classes-introduction-to-github#11480] opened 2017-11-07 16:45 UTC
Hello! :wave: Please add me as a collaborator to this repo. 

(Repo? Did I miss a payment?)

**Comment by hectorsector** [comment] 2017-11-09 01:35
This is a duplicate of #11485.

**Closed by hectorsector** 2017-11-09 01:35 UTC
